### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-war-simulator#1]
Hola,

He revisado el contenido de README y la configuración del equipo:
- El equipo debe estar compuesto por 3 a 4 estudiantes. Actualmente este equipo tiene únicamente 2 integrantes: https://github.com/orgs/aigora/teams/war-simulator/members. Por tanto, no es válido.
- La propuesta es muy poco ambiciosa. No es suficiente para cumplir los requisitos que se plantean en el trabajo.
- Debéis eliminar los corchetes al rellenar el README.

**Comment by DanielGarciaArana** [comment]
Hola, 

Estamos 3 solo que falta por unirse un integrante que está teniendo problemas. En cuanto a la ambición del proyecto teniamos pensado añadir más cosas como que el usuario pueda elegir que 2 bots se enfrentan cada ronda o que la probabilidad de cada bot para ganar una ronda aumente a medida que gana más batallas. La verdad es que no tenemos del todo claro cual es el nivel mínimo exigido. Nos gustaria saber cuanto antes que hay que hacer para poder empezar ya.

**Comment by oscarperpinan** [comment]
He comprobado que ya sois 3 integrantes en el equipo. 
Según avancéis en el desarrollo del proyecto os daré orientaciones para que el trabajo tenga un nivel adecuado. En cualquier caso, los requisitos mínimos están definidos en moodle.
Las tareas que debéis realizar son las mismas que el resto de equipos, y que ya he indicado en mensajes anteriores.
