### ISSUE TITLE
Librerías no estándar

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-war-simulator#11]
Hola,

Salvo excepciones justificadas previamente acordadas conmigo, debéis evitar el uso de librerías no estándar. Estas librerías impiden la [portabilidad del código](https://es.wikipedia.org/wiki/Portabilidad). 

En particular, el código emplea la librería `windows.h`:

https://github.com/aigora/twIE_2021-war-simulator/blob/30eec770abfc28d07438c6194705a228c7812b76/Main.c#L5

**Comment by DanielGarciaArana** [comment]
Necesito la libreria <windows.h> para la función congelar_tiempo. No se de que otra manera podria parar el programa durante un tiempo T.

**Comment by oscarperpinan** [comment]
Por ejemplo: https://www.geeksforgeeks.org/time-delay-c/

**Comment by DanielGarciaArana** [comment]
Vale gracias ya lo he solucionado
