### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-war-simulator#4]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by lquintanac** [comment]
Una vez subido el archivo de diagrama de flujo recordad cerrar esta issue. Teniendo cerradas todas las issues de la milestone Versión alfa recordad cerrarla también.

**Comment by iglesiascaballeropablo** [comment]
![diagrama de flujo](https://user-images.githubusercontent.com/79968665/119315759-7a5cd880-bc76-11eb-9f6e-bd361258f92c.png)

[diagrama de flujo (1).pdf](https://github.com/aigora/twIE_2021-war-simulator/files/6538012/diagrama.de.flujo.1.pdf)
